[entryPoints]
  [entryPoints.web]
    address = ":80"

[api]
  insecure = true

[providers.docker]
  endpoint = "unix:///var/run/docker.sock"
  exposedByDefault = false

[providers.file]
  filename = "dynamic_conf.toml"

[log]
  level = "INFO"

[ping]
